version: "3.1"

services:
  mysql:
    image: docker.io/bitnami/mysql:8.0
    ports:
      - '3306:3306'
    volumes:
      - 'mysql_data:/bitnami/mysql/data'
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: test
      MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
    healthcheck:
      test: [ 'CMD', '/opt/bitnami/scripts/mysql/healthcheck.sh' ]
      interval: 15s
      timeout: 5s
      retries: 6

  redis:
    image: redis:6
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  redis-ui:
    image: patrikx3/p3x-redis-ui
    ports:
      - '7843:7843'
    volumes:
      - ./tmp/redis-ui-settings:/settings

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local
